channels:
  - conda-forge
  - defaults
dependencies:
  - pandas>=1.4
  - pyarrow>=7.0.0
  - ipython
  - pytables
  - python-graphviz
  - conda-libmamba-solver
  - conda-build
  - conda-verify
  - conda-smithy
  - gh
  - boa
  - pip
  - modin
  - dask>=2022.8.0
  - openjdk==8.*
  - pyspark==3.2.*
  - openpyxl
  - sqlalchemy
  - pytables

  - twine
  - flake8
  - pylint
  - pandas-stubs
  - mkdocs
  - papermill
  - werkzeug==2.0

  - jupyterlab
  - jupyterlab-git
  - dask-labextension
  - voila

  - pytest>=2.8
  - pytest-xdist
  - pytest-mock
  - pytest-cov>=3.0.0

  - pip:
      - pip
      - daff
      - pytype
